---

- name: Check if /etc/kubernetes/pki exists
  stat:
    path: /etc/kubernetes/pki
  register: pki_dir
  
- name: Create /etc/kubernetes/pki if it does not exist
  file:
    path: /etc/kubernetes/pki
    state: directory
    owner: root
    group: root
  when: pki_dir.stat.exists == False
  
- name: Check if ca.crt exists
  stat:
    path: /etc/kubernetes/pki/ca.crt
  register: ca_crt
  
- name: Check if ca.key exists
  stat:
    path: /etc/kubernetes/pki/ca.key
  register: ca_key
  
- name: Copy certs to /etc/kubernetes/pki
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/pki
    owner: root
    group: root
    mode: 0600
  loop:
    - ca.crt
    - ca.key
  when: not ca_crt.stat.exists and not ca_key.stat.exists

- name: Set permissions of ca.crt to 0644
  file:
    path: /etc/kubernetes/pki/ca.crt
    mode: 0644
  when: ca_crt.stat.exists

- name: Run kubeadm init
  command: kubeadm init --config /vagrant/InitConfiguration.yaml

- name: Create .kube directory for user
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0700

- name: Copy kubeconfig to .kube directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
    remote_src: true
    mode: 0600
