---

- hosts: all
  gather_facts: yes
  become: true
  
  tasks:
    - name: Install Cilium CNI
      tags: cilium
      block:
        # source: https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
        - name: Set CILIUM_CLI_VERSION to latest stable version
          set_fact:
            cilium_cli_version: "v0.16.18"

        - name: Set CLI_ARCH to amd64
          set_fact:
            cli_arch: "amd64"

        - name: Change CLI_ARCH to arm64 if architecture is aarch64
          set_fact:
            cli_arch: "arm64"
          when: ansible_architecture == "aarch64"

        - name: Download cilium-cli.tar.gz
          get_url:
            url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-{{ cli_arch }}.tar.gz"
            dest: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
            checksum: "sha256:https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
          register: get_url_result
          until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
          retries: 3
          delay: 5

        - name: Extract cilium-cli to /usr/local/bin
          become: yes
          unarchive:
            src: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
            dest: /usr/local/bin
            remote_src: yes

        - name: Remove downloaded files
          file:
            path: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
            state: absent

        - name: Install Cilium
          command: cilium install --version 1.16.1
          become_user: vagrant

        - name: Wait 5m0s for Cilium to report no warnings and errors
          command: cilium status --wait
          become_user: vagrant

    - name: Install Calico CNI
      tags: calico
      block:
        - name: Set Calico version
          set_fact:
            calico_version: "v3.29.2"

        - name: Install tigera operator
          kubernetes.core.k8s:
            src: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml"
            state: present
          become_user: vagrant

        - name: Install custom resources
          kubernetes.core.k8s:
            src: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/custom-resources.yaml"
            state: present
          become_user: vagrant

        - name: Wait for tigera-operator to become ready
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Deployment
              metadata:
                name: tigera-operator
                namespace: tigera-operator
            wait: True
            wait_condition:
              reason: MinimumReplicasAvailable
              type: Available
              status: True
          become_user: vagrant

        # Fix for current calico deployment
        - name: Create secret for calico-cni-plugin ServiceAccount
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Secret
              metadata:
                name: calico-cni-plugin
                namespace: calico-system
                annotations:
                  kubernetes.io/service-account.name: calico-cni-plugin
              type: kubernetes.io/service-account-token
          become_user: vagrant
