---

- hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install nfs server
      tags: nfs
      block:
        - name: Install nfs-kernel-server
          apt:
            name: nfs-kernel-server
            state: present
          register: apt_result
          until: apt_result is success
          retries: 3
          delay: 5

        - name: Create directory to share via NFS server
          file:
            path: /opt/sfw/
            state: directory
            mode: 1777
            recurse: yes

        - name: Create test file to share via NFS server
          copy:
            content: "Hello World!"
            dest: /opt/sfw/test.txt
            mode: 0644

        - name: Add NFS directory to /etc/exports
          lineinfile:
            path: /etc/exports
            line: "/opt/sfw *(rw,sync,no_root_squash,subtree_check)"
            state: present
            create: yes

        - name: Reload exportfs
          command: exportfs -ra

    - name: Install nfs-subdir-external-provisioner
      tags: nfs
      block:
        - name: Add nfs-subdir-external-provisioner Helm repo
          kubernetes.core.helm_repository:
            name: nfs-subdir-external-provisioner
            repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
          become_user: vagrant

        - name: Install nfs-subdir-external-provisioner Helm chart
          kubernetes.core.helm:
            name: nfs-subdir-external-provisioner
            chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
            namespace: nfs-subdir-external-provisioner
            create_namespace: true
            update_repo_cache: true
            set_values:
              - value: nfs.server=192.168.100.10
                valueType: string
              - value: nfs.path=/opt/sfw/
                valueType: string
          become_user: vagrant