---

k8s_repo_version: '1.30'
k8s_package_version: "{{ k8s_repo_version }}.5-1.1"

cni_plugins_version: '1.5.1'
cni_plugins_url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v{{ cni_plugins_version }}.tgz"
